spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/activite?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hrbroot

server:
#  tomcat:
#   http://127.0.0.1:8071/apiyml/person/save?name=anything01  tomcat 路劲可以自己就设置 context-path
#    uri-encoding: utf-8
#  port: 8071
#  servlet:
#    context-path: /apiyml

#  http://127.0.0.1:8071/person/save?name=anything01  netty 路径没有context-path
  port: 8071
  netty:
    connection-timeout: 20
